swagger: "2.0"
info:
    description: "Permissions System"
    version: "1.0.0"
    title: "Permissions Service"
    termsOfService: "https://terms.tracklin.es/permissions"
    contact:
        email: "permissions@tracklin.es"
    license:
        name: "MIT"
        url: "https://opensource.org/licenses/MIT"
host: "permissions.tracklin.es"
basePath: "/v1"
tags:
    - name: "Permissions"
      description: "System Permissions"
      externalDocs:
          description: "System Permissions"
          url: "https://docs.tracklin.es/permissions/permissions"
    - name: "Permission"
      description: "User Permissions"
      externalDocs:
          description: "User Permissions"
          url: "https://docs.tracklin.es/permissions/permission"
schemes:
    - "https"
paths:
    /permission:
        post:
            tags:
                - "Permission"
            summary: "Add User Permission"
            operationId: "addUserPermission"
            consumes:
                - "application/json"
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  required: true
                  type: "string"
                - name: "body"
                  in: "body"
                  description: "User Permission Object"
                  required: true
                  schema:
                      $ref: "#/definitions/UserPermission"
            responses:
                405:
                    description: "Invalid User Permission Object"
                    schema:
                        $ref: "#/definitions/ApiResponse"
                200:
                    description: "Successfully Added User Permission"
                    schema:
                        $ref: "#/definitions/UserPermissions"
            security:
                - user_auth:
                    - "write:permissions"
                    - "read:permissions"
        get:
            tags:
                - "Permission"
            summary: "Get All The Permissions for a User"
            operationId: "getAllUserPermissions"
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  required: true
                  type: "string"
            responses:
                200:
                    description: "All User Permissions"
                    schema:
                        $ref: "#/definitions/UserPermissions"
            security:
                - user_auth:
                    - "read:permissions"
    /permission/{permissionId}:
        get:
            tags:
                - "Permission"
            summary: "Get User Permission"
            operationId: "getUserPermission"
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  required: true
                  type: "string"
                - name: "permissionId"
                  in: "path"
                  type: "integer"
                  format: "int64"
                  required: true
            responses:
                200:
                    description: "Get User Permission"
                    schema:
                        $ref: "#/definitions/UserPermission"
            security:
                - user_auth:
                    - "read:permissions"
        delete:
            tags:
                - "Permission"
            summary: "Delete User Permission"
            operationId: "deleteUserPermission"
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  required: true
                  type: "string"
                - name: "permissionId"
                  in: "path"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                200:
                    description: "Deleted User Permission"
                    schema:
                        $ref: "#/definitions/ApiResponse"
            security:
                - user_auth:
                    - "read:permissions"
                    - "write:permissions"
    /permissions:
        post:
            tags:
                - "Permissions"
            summary: "Add System Permission"
            description: ""
            operationId: "addSystemPermission"
            consumes:
                - "application/json"
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  required: true
                  type: "string"
                - name: "body"
                  in: "body"
                  description: "System Permission Object"
                  required: true
                  schema:
                      $ref: "#/definitions/SystemPermission"
            responses:
                405:
                    description: "Invalid System Permission Object"
                    schema:
                        $ref: "#/definitions/ApiResponse"
                200:
                    description: "Successfully Added System Permission"
                    schema:
                        $ref: "#/definitions/SystemPermission"
            security:
                - system_auth:
                    - "write:permissions"
                    - "read:permissions"
        get:
            tags:
                - "Permissions"
            summary: "Get All Permissions"
            description: ""
            operationId: "getAllSystemPermissions"
            produces:
                - "application/json"
            responses:
                200:
                    description: "All System Permissions"
                    schema:
                        type: "array"
                        items:
                            $ref: "#/definitions/SystemPermission"
            security:
                - system_auth:
                    - "read:permissions"
    /permissions/{permissionId}:
        get:
            tags:
                - "Permissions"
            summary: "Get System Permission"
            operationId: "getSystemPermission"
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  type: "string"
                  required: true
                - name: "permissionId"
                  in: "path"
                  description: "System Permission Id"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                200:
                    description: "System Permission"
                    schema:
                        $ref: "#/definitions/SystemPermission"
                400:
                    description: "Invalid System Permission Id"
                    schema:
                        $ref: "#/definitions/ApiResponse"
                404:
                    description: "Unknown System Permission Id"
                    schema:
                        $ref: "#/definitions/ApiResponse"
            security:
                - system_auth:
                    - "write:permissions"
                    - "read:permissions"
        delete:
            tags:
                - "Permissions"
            summary: "Delete System Permission"
            operationId: "deleteSystemPermission"
            description: ""
            produces:
                - "application/json"
            parameters:
                - name: "api_key"
                  in: "header"
                  required: true
                  type: "string"
                - name: "permissionId"
                  in: "path"
                  description: "System Permission Id"
                  required: true
                  type: "integer"
                  format: "int64"
            responses:
                400:
                    description: "Invalid System Permission Id"
                    schema:
                        $ref: "#/definitions/ApiResponse"
                404:
                    description: "System Permission Not Found"
                    schema:
                        $ref: "#/definitions/ApiResponse"
                200:
                    description: "Successfully Deleted System Permission"
                    schema:
                        $ref: "#/definitions/ApiResponse"
            security:
                - system_auth:
                    - "write:permissions"
                    - "read:permissions"
securityDefinitions:
    system_auth:
        type: "oauth2"
        authorizationUrl: "https://permissions.tracklin.es/oauth/dialog"
        flow: "implicit"
        scopes:
            write:permissions: "Modify System Permissions"
            read:permissions: "Read System Permissions"
    user_auth:
        type: "oauth2"
        authorizationUrl: "https://permissions.tracklin.es/oauth/dialog"
        flow: "implicit"
        scopes:
            write:permissions: "Modify User Permissions"
            read:permissions: "Read User Permissions"
    api_key:
        type: "apiKey"
        name: "api_key"
        in: "header"
definitions:
    UserPermissions:
        type: "object"
        required:
            - "userId"
        properties:
            userId:
                type: "integer"
                format: "int64"
            permissions:
                type: "array"
                items:
                  $ref: "#/definitions/UserPermission"
    UserPermission:
        type: "object"
        required:
            - "id"
        properties:
            id:
                type: "integer"
                format: "int64"
            name:
                type: "string"
    SystemPermission:
        type: "object"
        required:
            - "name"
            - "status"
        properties:
            id:
                type: "integer"
                format: "int64"
            name:
                type: "string"
            status:
                type: "string"
                description: "Status Of Permission"
                enum:
                    - "unavailable"
                    - "allowed"
                    - "disabled"
    ApiResponse:
        type: "object"
        properties:
            code:
                type: "integer"
                format: "int64"
            type:
                type: "string"
            message:
                type: "string"
